export const styles = {
  container: {
    // minWidth: 450,
    width: "100%",
    minHeight: 266.14,
    maxHeight: 266.14,
    textAlign: "left",
    boxShadow: "0 0 5px 3px rgba(100 100 100 / 20%)",
    cursor: "pointer",
    minHeight: "220",
    color: "#111",
  },
  taskContainer: {
    backgroundColor: "transparent",
    paddingLeft: "0px",
    paddingRight: "0px",
    margin: "8px",
    marginTop: "0px",
    marginBottom: "0px",
    width: "100%",
    borderRadius: "4px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  individualTask: {
    fontSize: "13px",
    margin: "0px",
    paddingLeft: "0px",
    paddingRight: "5px",
    display: "flex",
    alignItems: "center",
    margin: "0px",
    color: "#fff",
    fontWeight: "bold",
  },
  button: {
    position: "relative",
    top: "-60px",
    left: "78%",
    cursor: "pointer",
    fontSize: "12px",
    marginTop: "20px",
    background: "#f4f4f4",
    color: "#111",
    // border: "1px solid #fff",
    background: "rgba(0, 0, 255, 0.6)",
    color: "#f5f5f5",
    fontWeight: "bold",
  },
  inputStyle: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#fff",
    backgroundColor: "#00f1",
    background: "rgba(255,255,255,0.2)",
    paddingLeft: "10px",
    paddingTop: "0px",
    paddingBottom: "0px",
    marginTop: "5px",
    marginBottom: "0px",
    border: "1px solid rgba(153, 153, 153, 0.1)",
    width: "100%",
    borderRadius: "5px",
  },
};
